[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200

lib_deps =
    makuna/RTC @ ^2.3.5
    bblanchon/ArduinoJson @ ^7.0.3

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_190703
